[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = """
lua vim.g.vim_json_syntax_conceal = '0'
"""

[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = ['yaml']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'yuezk/vim-js'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx']

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx']
hook_add = """
au BufNewFile,BufRead *.prisma setfiletype graphql
"""

[[plugins]]
repo = 'styled-components/vim-styled-components'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescript.tsx']

[[plugins]]
repo = 'neoclide/jsonc.vim'
on_ft = ['jsonc']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = """
lua vim.g.go_disable_autoinstall = '1'
lua vim.api.nvim_set_keymap('n', '<Leader>gr', ':GoRun<CR>', { noremap = true })
"""

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']
hook_add = """
lua vim.api.nvim_set_keymap('n', '<Leader>1', ':A<CR>', { noremap = true })
"""

[[plugins]]
repo = 'tbastos/vim-lua'
on_ft = ['lua']
